import = [
    "~/.config/alacritty/themes/themes/tokyo-night.toml"
]

[window]
dimensions = {columns = 150, lines = 48}

[font]
normal = {family = "JetBrainsMono Nerd Font", style = "Regular"}
size = 11.5

