import = [
    "~/.config/alacritty/themes/themes/tokyo-night.toml"
]

[window]
dimensions = {columns = 120, lines = 40}

[font]
normal = {family = "JetBrainsMono Nerd Font", style = "Regular"}
size = 14

